version: '3.9'

services:

  mongodb:
    image: mongo
    restart: always
    container_name: cashback-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pulseid
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017  
    networks: 
      - mongo-network  
    volumes:
      - mongodata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    container_name: cashback-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: cashback-mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pulseid
      ME_CONFIG_BASICAUTH_USERNAME: pulseid
      ME_CONFIG_BASICAUTH_PASSWORD: pulseid123
    depends_on:
      - mongodb
    networks: 
      - mongo-network     

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: cashback-web
    container_name: cashback-web
    ports:
      - 4001:4001
    environment:
      DATABASE: admin
      DATBASE_URL: mongodb://cashbackapp:pulseid@mongodb:27017/
    depends_on:
      - mongodb
    networks: 
      - mongo-network    

volumes:
  mongodata:  

networks: 
  mongo-network:
    driver: bridge  